module.exports = {
    DEBUG: true,
    ENCRYPT_DATA: false,
    ENABLE_HASHING_CHECKS: false,



    //errors
    RESULT_OK: 0,
    ERROR_INTEGRITY_FAILED: 1,

    ERROR_INVALID_REQUEST: 2,
    ERROR_INVALID_USERNAME_OR_PASSWORD: 3,
    ERROR_INTERNAL_SERVER_ERROR: 4,

    ERROR_INSUFFICIENT_DATA: 5,

    ERROR_INVALID_PRICE_RANGE: 6,

    ERROR_NO_RESULTS_FOUND: 7,

    ERROR_USER_NOT_FOUND: 8,

    ERROR_INVALID_EMAIL: 9
};