search:
	gcc -std=gnu99 -Wall corrector.c list_double.c  hashTableDisc.c

valgrind_search:
	valgrind ./a.out < $(T) --track-origins=yes --leak-check=full --show-leak-kinds=all --tool=memcheck

run:
	./a.out < $(F)

clean:	
	rm -rf *~

test20pal:
	./a.out < t.txt
	./a.out < t.txt
	./a.out < t.txt
	./a.out < t.txt
	./a.out < t.txt
	./a.out < t.txt
	./a.out < t.txt
	./a.out < t.txt
	./a.out < t.txt
	./a.out < t.txt
	./a.out < t.txt
	./a.out < t.txt
	./a.out < t.txt
	./a.out < t.txt
	./a.out < t.txt
	./a.out < t.txt
	./a.out < t.txt
	./a.out < t.txt
	./a.out < t.txt
	./a.out < t.txt
